[package]
name = "rs-surflog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
clap = { version = "4.5.3", features = ["derive"] }
homedir = "0.2.1"
rusqlite = "0.31.0"
