[package]
name = "surflog"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli"
path = "src/main-cli.rs"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.35"
clap = { version = "4.5.3", features = ["derive"] }
expanduser = "1.2.2"
log = "0.4.22"
rusqlite = "0.31.0"
